apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: global-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Global Dev Project
  
  sourceRepos:
  - 'https://github.com/opsguideme/argocd-example-apps.git'

  destinations:
  - namespace: guestbook
    server: https://kubernetes.default.svc
    name: in-cluster

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
